Database/Choices-FirstScreen.swift
Database/StartScreen.swift
Database/ViewController.swift

Adds "back to map" buttons for levels 1 and 2 (iPod and boyfriend scenarios). Removes extraneous back button that appears when home icon on map is clicked.

Back Button Fixes

---

Powerup.xcodeproj/project.pbxproj
Powerup/Accessories.swift
Powerup/AppDelegate.swift
Powerup/Choices-EndScreen.swift
Powerup/Choices-FifthScreen.swift
Powerup/Choices-FirstScreen.swift
Powerup/Choices-FourthScreen.swift
Powerup/Choices-SecondScreen.swift
Powerup/Choices-SixthScreen.swift
Powerup/Choices-ThirdScreen.swift
Powerup/Clothes.swift
Powerup/CustomizeAvatar.swift
Powerup/DressingRoom2.swift
Powerup/Hair.swift
Powerup/MapScreen.swift
Powerup/Scene4.swift
Powerup/Scene5.swift
Powerup/Scene6.swift
Powerup/Scene7.swift
Powerup/SecondViewController.swift
Powerup/StartScreen.swift
Powerup/ThirdViewController.swift
Powerup/ViewController.swift
PowerupTests/PowerupTests.swift

Ran entire codebase through Xcode's Swift 3 conversion tool.

Update Codebase to Swift 3

---

Powerup/StartScreen.swift

The Start Screen had some lines of code that did not update with Swift 3 and I updated them.

Updated orientation value to follow Swift 3 conventions

---

Powerup/CustomizeAvatar.swift

The left and right buttons while choosing a Custom Avatar do not stop,
maintaining the flow of the app.

Pull Request for Enhancement of Left and Right button while Avatar Customisation - Issue #51

---

Powerup/Base.lproj/Main.storyboard

Made the border to be able to auto layout so that no issues comes due to different phone sizes. The pull request contains chainges only to the background and User Bar in the make up room. Many more updations are required but we need a discussion before doing that.

Autolayout : Added initial Auto layout bordering for background.

---

Powerup/Base.lproj/Main.storyboard
Powerup/ShopViewController.swift

* Players can now try out different accessories without actually purchasing them.
* Added a Purchase Button. When pressed, the player would purchase all of the selected accessories.
* Added a Total Cost Label, showing the sum of the prices of the selected accessories.
* Added a Revert Button. Players can now revert to the original avatar after selecting different accessories by pressing it.
* Added warning dialogues when Purchase Button / Revert Button is pressed.
#94 #95 solved.

Reworked ShopViewController to fix issue #94 #95

---

README.md

Added Travis CI "build/passing" badge to the repo readme page.
#118 Solved.

Added Travis badge for the repo

---

Powerup/CustomizeAvatarViewController.swift
Powerup/ResultsViewController.swift

This is a task for Google code-in 2017, I fixed the spelling error and added the correct error message. There was no 'alright' button as described in the issue so I skipped that, as the problem wasn't there.
Fixes #112 
no testing needed, minor changes in messages.

fixed error messages for issue #112

---

Powerup/Base.lproj/Main.storyboard
Powerup/ScenarioViewController.swift

In some screen sizes, all three dialogue options can't be seen and for long dialogue options, the full text is not showing. This fixes both problems by setting TableView cell height to one-third of the TableView size and auto-shrinking the text so all of it can be seen. (The PR for dynamic cells is still open but I have closed the other PR relating to this issue)
Fixes #199 and #143
- Code
Ran the code on emulators of different sizes.

Show all dialogue options and fix issue of text getting cut off

---

Powerup/ShopViewController.swift

Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.
- Code
- User Interface
**Code**
Tested on iPhone Simulator in various devices
My PR follows the style guidelines of this project
I have performed a self-review of my own code or materials
I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
My changes generate no new warnings 
My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
I have added tests that prove my fix is effective or that my feature works

Hide empty display boxes in ShopViewController

---

README.md

I just fixed some formatting issues so that the whole document is now easier to read.
Tutorial Screenshots:

Program:GCI Learn markdown and beautify some documentation

---

Powerup/ShopViewController.swift

Purchase warning change as per suggestion.
Fixes #215
- Code

Purchase Warning Change.

---

CONTRIBUTING_GUIDELINES.md

Fixed broken links
Fixes # [ISSUE]
- Documentation

Fixed broken links

---

Powerup/Base.lproj/Main.storyboard
Powerup/CompletedViewController.swift
Powerup/MapViewController.swift

naming the unamed segue in project.All the unamed segues are named because unamed segues was throwing nil value.
Fixes #237
- Code
All the segues named are tested.

naming the unnamed segue and replacing debugprint with assertion Failure

---

Powerup/Base.lproj/Main.storyboard
Powerup/MapViewController.swift
Powerup/ResultsViewController.swift

Added continue button functionality to move directly to next Scenario and making it consistent with android application.
Fixes #233 #133 
- Code
- User Interface
- New feature (non-breaking change which adds functionality pre-approved by mentors)
Continue button functionality has been tested in simulator.

Adding Continue button functionality 

---

Powerup/Accessory.swift
Powerup/CompletedViewController.swift
Powerup/MapViewController.swift
Powerup/ResultsViewController.swift

Also fixed some compiler warnings
Fixed Swift 4 deprecations in Accesory.swift.
Also fixed some compiler warnings in CompletedViewController.swift.
Fixes #263
- Code
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.
The fixes are pretty isolated. I've run the app the ensure there were no new warnings or changes.

Fixed Swift 4 deprecations

---

Powerup.xcodeproj/project.pbxproj
Powerup/AboutViewController.swift
Powerup/OOC-Event-Classes/PopupEventPlayer.swift
Powerup/ScenarioViewController.swift
PowerupUITests/PopupEventPlayerTests.swift

Fixes #277 
Added UI test for PopupEventPlayer class.
- I added a popup to the about controller. It's quick to get to for testing live popups, and I think it's cute but it doesn't have to stay there. It says "Made with ♥ by Systers Open Source".
- Code
- New feature (non-breaking change which adds functionality pre-approved by mentors)
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.
UI tests pass in Xcode.

Issue 277 ui tests for PopupEventPlayer

---

Powerup.xcodeproj/project.pbxproj
Powerup/OOC-Event-Classes/PopupEventPlayer.swift
PowerupTests/PopupEventPlayerUnitTests.swift
PowerupUITests/StorySequencePlayerTests.swift

Fixes #286 
Added unit tests for PopupEventPlayer. First test mocks different cases of the model to ensure that the player can be created as expected.
The second loops through all real models, creates a mock popup, and checks that each has strings where we expect them, has or doesn't have an image as expected (this also serves as a check that the filename is correct), and that it plays sound if we expect it.
- Code
- New feature (non-breaking change which adds functionality pre-approved by mentors)
Tests pass in on the iOS 9 and 11 simulators.

Issue 286 popup unit test

---

Powerup.xcodeproj/project.pbxproj
Powerup/OOC-Event-Classes/StorySequenceModel.swift
Powerup/OOC-Event-Classes/StorySequencePlayer.swift
PowerupTests/StorySequencePlayerUnitTests.swift

Fixes #285
Added unit test for StorySequencePlayer dataset. It loops through and checks that strings match existing file names and enums.
- Code
- New feature (non-breaking change which adds functionality pre-approved by mentors)
Tests pass in on the iOS 9 and 11 simulators.

Issue 285 storysequence unit tests

---

Powerup/Base.lproj/Main.storyboard
PowerupUITests/StorySequencePlayerTests.swift

Updated the storyboard with accessibility identifiers for the home scenario button on the map view controller and the new game button on the start view controller.
Updated the StorySequencePlayer UI tests to always use the accessibility IDs in order to avoid the os version inconsistencies with element child matching.
Fixes #290 
- Code
The tests run locally on iOS 9 and 11.

Issue 290 accessibility

---

Powerup/OOC-Event-Classes/StorySequencePlayer.swift

Fixed StorySequencePlayer to account for the onscreen black area in the status bar.
Fixes #293 
- Code
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.
Runs as expected in simulator.

Account for black area in iPhoneX onscreen status bar

---

Powerup/OOC-Event-Classes/PopupEvents.swift

Removes an extra new line that caused a codacy error.

Removed extra line at bottom
